// storage 表格自定义列的key
export const STORAGE_KEY_GRID_COLUMNS = 'NOM_STORAGE_KEY_GRID_COLS'

// 表格自定义列宽度的 key
export const STORAGE_KEY_GRID_COLS_WIDTH = 'NOM_STORAGE_KEY_GRID_COLS_WIDTH'

// 表格固定列的 key
export const STORAGE_KEY_GRID_COLS_FIXED = 'NOM_STORAGE_KEY_GRID_COLS_FIXED'

// 分页器缓存分大小的 key
export const STORAGE_KEY_PAGER_CACHEABLE = 'NOM_STORAGE_KEY_PAGER_CACHE'
