define([
  './basic.js',
  './empty.js',
  './styles.js',
  './align.js',
  './ellipsis.js',
  './lazy-load.js',
  './lazy-load-remote.js',
  './sort.js',
  './sort-cacheable.js',
  './filter.js',
  './sort-columns.js',
  './row-sortable.js',
  './row-sortable-custom.js',
  './resizable.js',
  './frozen-header.js',
  './pin.js',
  './colspan.js',
  './column-auto-width.js',
  './auto-merge.js',
  './summary.js',
  './multi-summary.js',
  './multiple-header.js',
  './highlight-col.js',
  // './column-type.js',
  './column-tools.js',
  './row-checkable.js',
  './row-checkable-type.js',
  './row-checkable-events.js',
  './row-checkable-render.js',
  './custom-columns.js',
  './tree-grid.js',
  './tree-grid-flat-data.js',
  './tree-grid-indicator.js',
  './row-expandable.js',
  './nest-grid.js',
  './append-row.js',
  './cascade.js',
  './cascadeCheckParent.js',
  './cascadeCheckChildren.js',
  './cascadeUncheckChildren.js',
  './partial-checked.js',
  './editable.js',
  './editable-click.js',
  './td-edit.js',
  './td-edit-always.js',
  // './edit.js',
  // './full-edit.js',
  './nested-summary.js',
  './sticky.js',
  './sticky-window.js',
], function () {
  return {
    title: 'Grid',
    subtitle: '高级表格',
    demos: Array.prototype.slice.call(arguments),
  }
})
