name: Deploy Doc

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Intall, Build
        run: |
          npm i
          npm run build
        env:
          CI: true

      - name: Copy Doc Site
        run: mkdir doc-sites && cp -rif ./{components,dist,docs,libs,index.html,index.js,CHANGELOG.md,commitlint.md,release.md,README.md,LICENSE,.nojekyll} doc-sites
        env:
          CI: true

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          CI: true
          PROGRESS: none
          GIT_CONFIG_NAME: Jerry
          GIT_CONFIG_EMAIL: jerry.zhou@wetrial.com
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: 'doc-sites/'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: doc-sites/ # The folder the action should deploy.
